apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-chartservice
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: chartservice
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: helm-chart
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
      - values.yaml```
